services:
  - type: web
    name: ai-summarizer-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SITE_URL
        sync: false
      - key: SITE_NAME
        value: AI Summarizer
    healthCheckPath: /ping
